services:

  ##### MYSQL DATABASE #####
  database:
    image: mysql
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_DATABASE: 'wasaphoto'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-database:/var/lib/mysql
      - ./mysql-exporter-permissions.sql:/docker-entrypoint-initdb.d/mysql-exporter-permissions.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  database-exporter:
    image: prom/mysqld-exporter
    container_name: database-exporter
    restart: unless-stopped
    command: 
      - --mysqld.address=database:3306
      - --mysqld.username=exporter
    environment:
      MYSQLD_EXPORTER_PASSWORD: "exporter"
    ports:
      - "9104:9104"
    depends_on:
      database:
        condition: service_healthy

  ##### WASAPHOTO #####
  backend:
    # image: docker.io/aleiis/wasaphoto-backend:v1.3.1
    image: aleiis/wasaphoto-backend-otel
    container_name: wasaphoto-backend
    ports:
      - "5000:5000"
    environment:
      - WASAPHOTO_CONFIG_FILE=/app/config.yml
    volumes:
      - ./wasaphoto-config.yaml:/app/config.yml
      - wasaphoto-data:/app/wasaphoto
      - wasaphoto-bin:/app/bin
    command: ["sh", "-c", "cp /app/webapi /app/bin/webapi && /app/bin/webapi"]
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # frontend:
  #   image: docker.io/aleiis/wasaphoto-frontend:v1.1
  #   container_name: wasaphoto-frontend
  #   ports:
  #     - "9191:80"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "50m"
  #       max-file: "3"

  frontend:
    image: aleiis/wasaphoto-frontend-otel:latest
    container_name: wasaphoto-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./otel-instrument.js:/usr/share/nginx/html/assets/otel-instrument.js
      - ./opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
    ports:
      - "9191:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  ##### GRAFANA #####
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
    ports: 
      - '3003:3000'
    volumes:
      - grafana-data:/var/lib/grafana

  ##### LOKI #####
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/config/config.yaml
    command: -config.file=config/config.yaml

  ##### ALLOY #####
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

  ##### TEMPO (traces) #####
  # go-auto:
  #   image: otel/autoinstrumentation-go
  #   privileged: true
  #   pid: "host"
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
  #     - OTEL_GO_AUTO_TARGET_EXE=/app/bin/webapi
  #     - OTEL_SERVICE_NAME=webapi-auto
  #     - OTEL_PROPAGATORS=tracecontext,baggage
  #   volumes:
  #     - wasaphoto-bin:/app/bin/webapi
  #     - /proc:/host/proc
  #   depends_on:
  #     - backend
  #     - tempo

  # The envoy proxy is used to add tracing headers to the requests and 
  # forward them to the backend.
  envoy-front-proxy:
    image: envoyproxy/envoy:v1.31-latest
    ports:
      - "3000:3000"
    volumes:
      - ./envoy-front-proxy-config.yaml:/etc/envoy/envoy.yaml

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"  # otlp gRPC
      - "4318:4318"  # otlp http
    depends_on:
      - memcached

  ##### CADVISOR AND PROMETHEUS #####

  # cAdvisor (short for container Advisor) analyzes and exposes 
  # resource usage and performance data from running containers. 
  # cAdvisor analyzes all the Docker containers that are executing
  # in the same host as cAdvisor. It's not necessary to manually 
  # configure cAdvisor for each container, it already has access 
  # to the whole Docker system.   
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  # Prometheus must have a config YAML to scrape metrics from cAdvisor.
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus-config.yaml
    volumes:
    - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml:ro
    - prometheus-data:/prometheus
    depends_on:
    - cadvisor


  ##### CORTEX #####
  cortex:
    image: quay.io/cortexproject/cortex:v1.18.1
    container_name: cortex
    command:
      - -config.file=/config/cortex-config.yaml
    volumes:
      - ./cortex-config.yaml:/config/cortex-config.yaml:ro
    ports:
      - "9009:9009"
    healthcheck:
        test: wget -qO- http://localhost:9009/ready
        interval: 10s
        timeout: 10s
        retries: 3
    restart: unless-stopped

volumes:
  mysql-database: {}
  wasaphoto-data: {}
  grafana-data: {}
  prometheus-data: {}
  wasaphoto-bin: {}
