{
 "title": "Log Dashboard",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count ",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{container=~\"$container\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  },
  {
   "title": "Percentage for specified time of \"$searchable_pattern\"",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container=~\"$container\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Historical of \"$searchable_pattern\" ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval])) ",
     "legendFormat": "count"
    }
   ]
  }
 ]
}