global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: mysql
  static_configs:
  - targets:
    - database-exporter:9104

remote_write:
  - url: http://cortex:9009/api/v1/push
