# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

config_file: "config.yml"

# If a log file is not provided, stdout will be used.
# Folders will be created if they do not exist.
log_file: ""

# If debug is set to true, the log level will be set to debug
debug: false

# The image storage path is the path where the images will be stored
image_storage:
  path: "/app/wasaphoto/images"

# The database configuration is used to connect to the MySQL database
db:
  user: "admin"
  password: "admin"
  address: "mysql-database:3306"
  database: "wasaphoto"
  mysql_exporter:
    enabled: false
    user: "exporter"
    password: "exporter"
    address: "localhost"

# The web configuration is used to configure the API service
web:
  api_host: "0.0.0.0:3000"
  debug_host: "0.0.0.0:4000"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s

# OTLP Configuration
# otlp:
#   http_trace_exporter_endpoint: "otel-collector:4318"