{
 "title": "Docker global overview",
 "description": "Global overview of Docker monitoring with Prometheus and cAdvisor ",
 "tags": [
  "docker",
  "cadvisor",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interface", "label": "Interface", "query": { "query": "label_values(interface)" } }
  ]
 },
 "panels": [
  {
   "title": "Firing Alerts",
   "type": "alertlist",
   "description": "List with all the firing alerts.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 }
  },
  { "title": "Normal Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Top Containers CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (name)) * 100 / 16",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Containers Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(5, sum by(name) (container_memory_usage_bytes{image!=\"\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Total Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) * 100 / sum(machine_cpu_cores)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Total Usage Gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[$__rate_interval]) * 100) / sum(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "CPU Usage Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_user_seconds_total{name!=\"\"}[$__rate_interval])) * 100) / sum(machine_cpu_cores)",
     "legendFormat": "User"
    },
    {
     "expr": "(sum(rate(container_cpu_system_seconds_total{name!=\"\"}[$__rate_interval])) * 100) / sum(machine_cpu_cores)",
     "legendFormat": "Kernel"
    }
   ]
  },
  {
   "title": "CPU Usage Breakdown Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_user_seconds_total{image!=\"\"}[$__rate_interval])) * 100) / sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "(sum(rate(container_cpu_system_seconds_total{image!=\"\"}[$__rate_interval])) * 100) / sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval]))",
     "legendFormat": "Kernel"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"})",
     "legendFormat": "Hot"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes)/1024/1024"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"}) * 100/ sum(machine_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Rx $interface"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{image!=\"\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Tx $interface"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{image!=\"\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Rx $interface"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{image!=\"\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Tx $interface"
    }
   ]
  }
 ]
}